In [1]:
import numpy as np
import matplotlib.pyplot as plt
from perceptron import *

In [15]:
def perceptron_through_origin(data, labels, params={}, hook=None):
    """The Perceptron learning algorithm.

    :param data: A d x n matrix where d is the number of data dimensions and n the number of examples.
    :param labels: A 1 x n matrix with the label (actual value) for each data point.
    :param params: A dict, containing a key T, which is a positive integer number of steps to run
    :param hook: An optional hook function that is called in each iteration of the algorithm.
    :return:
    """
    T = params.get('T', 100)  # if T is not in params, default to 100
    (d, n) = data.shape
    theta = np.zeros((d, 1))
    theta_0 = 0
    for _ in range(T):
        if hook : hook((theta, theta_0))
        print(theta)
        for index, entry in enumerate(data.T):
            if labels[index] * linear_classify(entry, theta, theta_0) <= 0:
                print("mistake")
                theta = np.add(theta, (labels[index] * entry.reshape(d, 1)))
                print(theta)
                
    return theta

In [16]:
X = np.array([[2, 0, -1],
            [0, 2, -1]])
y = np.array([-1, 1, -1])


th = perceptron_through_origin(np.append(X, np.ones((1, X.shape[1])), axis = 0), y, params = {'T' : 2})
th
#th1, th0 = perceptron(X, y)

#print(f"original hypothesis: \n\ttheta = {th1.ravel()}, \n\ttheta zero = {th0}.\nNew hypothesis (through origin): \n\ttheta = {th.ravel()}")


[[0.]
 [0.]
 [0.]]
mistake
[[-2.]
 [ 0.]
 [-1.]]
mistake
[[-2.]
 [ 2.]
 [ 0.]]
mistake
[[-1.]
 [ 3.]
 [-1.]]
[[-1.]
 [ 3.]
 [-1.]]


array([[-1.],
       [ 3.],
       [-1.]])

In [4]:
def poly_powers(order):
    """
    Returns all powers for a polynomial of a given order.
    For example, if order is 2 (a, b), will return the powers for a and b to make [1, a, b, a^2, ab, b^2]
    """
    return [(k - i, i) for k in range(order + 1) for i in range(k + 1)]

In [5]:
def poly_transform_single(x, k):
    return np.array([((x[0] ** power[0]) * (x[1] ** power[1])) for power in poly_powers(k)])

In [6]:
def transform_polynomial_basis(X, k):
    if k not in range(5):
        raise ValueError("k can only be between 0 and 4")
    if X.shape[0] != 2:
        raise ValueError("X must be a 2 - dimensional array")
    output = np.zeros((len(poly_powers(k)), X.shape[1]), dtype = float)
    for i in range(output.shape[1]):
        output[:,i] = poly_transform_single(X[:,i], k)
    return output

In [7]:
np.set_printoptions(suppress=True)
X, transform_polynomial_basis(X, 4)

(array([[ 2,  3,  9, 12],
        [ 5,  2,  6,  5]]),
 array([[    1.,     1.,     1.,     1.],
        [    2.,     3.,     9.,    12.],
        [    5.,     2.,     6.,     5.],
        [    4.,     9.,    81.,   144.],
        [   10.,     6.,    54.,    60.],
        [   25.,     4.,    36.,    25.],
        [    8.,    27.,   729.,  1728.],
        [   20.,    18.,   486.,   720.],
        [   50.,    12.,   324.,   300.],
        [  125.,     8.,   216.,   125.],
        [   16.,    81.,  6561., 20736.],
        [   40.,    54.,  4374.,  8640.],
        [  100.,    36.,  2916.,  3600.],
        [  250.,    24.,  1944.,  1500.],
        [  625.,    16.,  1296.,   625.]]))

In [8]:
perceptron(X, y), perceptron_through_origin(transform_polynomial_basis(X, 1), y)

((array([[-24.],
         [ 37.]]),
  -3),
 array([[ -3.],
        [-24.],
        [ 37.]]))

In [9]:
def transform_polynomial_basis(data, order):
    from itertools import combinations_with_replacement as nCr
    from functools import reduce, partial
    from operator import mul
    def poly_basis(vector, order):
        print(vector)
        times = partial(reduce, mul)
        out = [1]
        for o in range(1, order+1):
            out.extend(list(map(times, nCr(vector, o))))
        return np.array(out).T
    out = []
    for vector in data.T:
        out.append(poly_basis(vector, order))
    return out

In [10]:
transform_polynomial_basis(X, 2)

[2 5]
[3 2]
[9 6]
[12  5]


[array([ 1,  2,  5,  4, 10, 25]),
 array([1, 3, 2, 9, 6, 4]),
 array([ 1,  9,  6, 81, 54, 36]),
 array([  1,  12,   5, 144,  60,  25])]