In [2]:
import numpy as np

In [3]:
x = np.array(
    [
        [2], 
        [3], 
        [5]
    ]
)
y = np.array(
    [
        [3], 
        [0], 
        [4]
    ]
    )

np.dot(x.T, y), np.dot(x, y.T)

(array([[26]]),
 array([[ 6,  0,  8],
        [ 9,  0, 12],
        [15,  0, 20]]))

In [4]:
B = np.array(
    [
        [3, 2, 0],
        [0, 4, 2],
        [5, 0, 1],
        [1, 3, 4]
    ]
)

In [5]:
B[1 : 3, 1 : 2]

array([[4],
       [0]])

In [11]:
def dot_vec (v1, v2):
    """
    Returns the dot product of two vectors.
    """
    return sum([a * b for a, b in zip(v1, v2)])


def dot(m1, m2):
    """
    Returns the dot product of two matrices.
    """
    res = np.zeros((m1.shape[0], m2.shape[1]), dtype = int)
    for i in range(m1.shape[0]): 
        for j in range(m2.shape[1]):
            res[i, j] = dot_vec(m1[i], m2.T[j])
    return res

A = np.array(
    [
        [4, 1, 0, 2],
        [2, 0, 1, 3]
    ]
)
B = np.array(
    [
        [3, 2, 0],
        [0, 4, 2],
        [5, 0, 1],
        [1, 3, 4]
    ]
)

dot(A, B)

array([[14, 18, 10],
       [14, 13, 13]])

In [7]:
data = np.array(
    [
        [1, 17, 9],
        [2, 21, 10],
        [3, 12, 17]
    ]
)

In [8]:
def transform(data):
    return np.dot(data, np.array([[0], [1], [1]]))

transform(data)

array([[26],
       [31],
       [29]])

In [15]:
data_dimensions = data [0 :, 1 : 3]
def hyp(data, theta, theta_zero):
    data_modded = np.append(data, np.ones(((data.shape[0], 1))), axis = 1)
    theta_modded = np.append(theta, theta_zero)
    return np.dot(data_modded, theta_modded)


hyp(data_dimensions, np.array([4, 5]), -100)

array([13., 34., 33.])